# imports and requirements
# kivy 2.0.0 - requires atleast kivy 2.0.0 to run sucessfully
# import platform kivy.utils.platform - to be able to detect the platform that the app is running on
#(android, ios, windows, linux, macos, etc)
# import rgba kivy.utils.get_color_from_hex - function to be able to convert colors in hex code to the rgba colorspace


#:kivy 2.0.0
#:import platform kivy.utils.platform
#:import rgba kivy.utils.get_color_from_hex
WindowManager:
    FilePickerScreen:
    DataAnalysis:

# FilePickerScreen is the screen that allows you to pick an image, and process it. this is where the analytics of the
#image are shown.
<FilePickerScreen>:
    name: "FPScreen"
    id: FilePicker
    # making a box layout to contain all widgets.
    BoxLayout:
        id: overallLayout
        orientation: 'vertical'
        height: self.minimum_height
        background_color: 'white'

        # making a box layout, to contain the Dropdown Menu, OCTOPAS Logo, and their icon.
        BoxLayout:
            id: headerLayout
            background_color: ''


            # making an image widget, and the source of the widget is set to the logo file.
            Image:
                source: 'OCTOPAS1.png'
                width: self.parent.width/self.image_ratio/6
#                height: self.parent.height/self.image_ratio/6
                allow_stretch: True
                keep_ratio: True

            # making an image widget, the source of the widget is set to the Icon file
            Image:
                source: 'Icon.ico'
                width: self.parent.width/(8*self.image_ratio)
                height: self.parent.height/(8*self.image_ratio)
#                allow_stretch: True
                keep_ratio: True

        # making an boxlayout, to contain the the file chooser, the analytics, and the buttons.
        BoxLayout:
            id: displayOverlay
            orientation: 'horizontal'
            padding: 10
            spacing: 10

            # creates the file chooser, and makes it list view instead of icon view
            FileChooserListView:
                id: filechooser
                rootpath: '/storage/emulated/0/' if platform == 'android' else '/'
                on_selection: FilePicker.selected(filechooser.selection)
                border: (10,10,10,10)

            # creates an image widget to contain the image to be processed.  by default ths source is set to the
            # 'PleasePickAnImage.png'
            Image:
                id: OilImage
                source: 'PleasePickAnImage.png'
                keep_ratio: True
                allow_stretch: True
                width: self.parent.width
                height: self.parent.width/self.image_ratio

        # creates a box layout to contain all of the labels, for the analytics.
        BoxLayout:
            id: analysisOverlay
            orientation: 'vertical'
            background_color: 'white'
            size_hint_y: None
            height: self.minimum_height
            padding: 10
            spacing:  root.height/30

            # label for the title, this label is what shows the error messages, what file is chosen, etc.
            Label:
                id: title
                color: rgba("#005c7a")
                text: ''
                halign: 'left'
                text_size: self.size
                size: (root.width, 15)
                font_size: (root.height / 15) * 0.5
            # creates a label to display the processing time.
            Label:
                id: processTime
                text: ''
                color: rgba("#005c7a")
                halign: 'left'
                text_size: self.size
                size: (root.width, 10)
                font_size: (root.height / 15) * 0.4

            # creates a label to area of the water
            Label:
                id: areaOfWater
                text: ''
                color: rgba("#005c7a")
                text_size: self.size
                halign: 'left'
                size: (root.width, 10)
                font_size: (root.height / 15) * 0.4


            # creates a label to display the area of the oil.
            Label:
                id: areaOfOil
                text: ''
                color: rgba("#005c7a")
                text_size: self.size
                halign: 'left'
                size: (root.width, 10)
                font_size: (root.height / 15) * 0.4

            # creates a label to display the area of the oil.
            Label:
                id: percentOfOil
                text: ''
                color: rgba("#005c7a")
                text_size: self.size
                halign: 'left'
                size: (root.width, 10)
                font_size: (root.height / 15) * 0.4

            # creates a label to display the length of the boom shown.
            Label:
                id: lengthOfBoom
                text: ''
                color: rgba("#005c7a")
                text_size: self.size
                halign: 'left'
                size: (root.width, 10)
                font_size: (root.height / 15) * 0.4

        # creates a box layout to contain all of the buttons.
        BoxLayout:
            id: buttonOverlay
            background_color: 'white'
            orientation: 'horizontal'
            size_hint_y: None
            height: 100 if 100 > root.height/8 else root.height/8
            padding: 10
            spacing: 10

            # creates the Pick an Image Button. this button calls the FilePicker.open function, every time the
            # button is released.  the inputs for the function are filechooser.path, which provides the path of the
            # file chosen. the 2nd input is the filechooser.selection, which essentially is the name of the file.

            Button:
                id: pickButton
                text: "Pick an Image!"
                on_release: FilePicker.open(filechooser.path, filechooser.selection)
                border: 15,15,15,15
                font_size: ((root.height + root.width) / 30) * 0.7
                size_hint: .3, 1
                size: 75, 100
                orientation: 'vertical'

            # creates the Process Button. this button calls the FilePicker.process function, every time the
            #button is released.
            Button:
                id: processButton
                text: "Process!"
                border: 15,15,15,15
                font_size: ((root.height + root.width) / 30) * 0.7
                size_hint: .3, 1
                orientation: 'vertical'
                on_release: FilePicker.process()


            # creates the clear button, this button calls the FilePicker.clear function every time the button is released.
            Button:
                id: clearButton
                text: "Clear!"
                border: 15,15,15,15
                font_size: ((root.height + root.width) / 30) * 0.7
                size_hint: .3, 1
                size: 75, 100
                orientation: 'vertical'
                on_release: FilePicker.clear()


# creates a third screen that allows you to see the analysis of the data; for future enhancements
<DataAnalysis>:
    name: "second"
