#:kivy 2.0.0
#:import platform kivy.utils.platform
WindowManager:
    FilePickerScreen:
    ProcessedImageScreen:


<FilePickerScreen>:
    name: "first"
    id: FilePicker
    BoxLayout:
        id: overallLay
        size: root.width, root.height
        BoxLayout:
            orientation: 'vertical'
            size_hint_x: .3
            Button:
                id: pickButton
                text: "Pick an \nImage!"
                on_release: FilePicker.open(filechooser.path, filechooser.selection)
                size_hint_y: .5
                size: self.texture_size
                orientation: 'vertical'
            Button:
                id: processButton
                text: "Process!"
                size_hint_y:.5
                size: self.texture_size
                on_release: FilePicker.process(filechooser.path, filechooser.selection)
            Button:
                id: clearButton
                text: "Clear!"
                on_release: FilePicker.clear(filechooser.path)

        FileChooserListView:
            id: filechooser
            rootpath: '/storage/emulated/0/' if platform == 'android' else '/'
            on_selection: FilePicker.selected(filechooser.selection)



#        Image:
#            id: oilImage
#                source: os.path.join(filechooser.path,  filechooser.selection[0])

<ProcessedImageScreen>:
    name: "second"



